### ISSUE TITLE
access denied (with administrator privilage)

### ISSUE THREAD

**Issue by Samthapa76** [KarthikUdyawar/data-cleaner#1]
windows 11 it says access denied it leavs a lot of files and after it says press enter to exit but it stay there i can make better batch file to delete this files than this file you created at least dig some stuff and see how to make apps then release

**Comment by KarthikUdyawar** [comment]
Hello @Samthapa76 ,

Thank you for bringing this issue to my attention.

### Access Denied
The script appears to be encountering access-denied errors even when run with administrator privileges. This can happen if certain files or directories are protected by the system or used by other applications. Please confirm if you ran the script in administrator mode.

### Remaining Files
Regarding the script leaving files behind, it's possible that some files cannot be deleted because they are currently in use. I'll investigate this further and look into improving the script to handle such cases more gracefully.

### Improvement Suggestions
I appreciate your offer to contribute a better batch file. Open-source projects thrive on community contributions, and I welcome any improvements you can suggest. Feel free to submit a pull request with your enhancements or share your ideas here.

### Next Steps
I'll be working on the following to improve the script:
- Investigate and fix the access-denied issues.
- Ensure that the script can handle files that are in use or protected.

Thank you again for your feedback. If you have any more details or suggestions, please share them. Together, we can make this tool more robust and useful for everyone.

Best regards,  
Karthik Udyawar

**Comment by KarthikUdyawar** [comment]
### Issue Update: Fix Access-Denied Issues and Enhance Cleanup Script
The changes have been successfully merged into the master branch. Here’s a summary of the updates:

- **Access-Denied Issues:** Added a check for administrator privileges to handle access-denied errors more effectively.
- **Improved Cleanup Handling:** Enhanced the script to handle file deletions and exceptions more gracefully.
- **Color-Coded Output:** Implemented color-coded messages for error reporting and status updates to improve readability.
- **README.md:** Updated the documentation to reflect the new changes and features.

You can find the latest release with these changes at: Release [v0.4](https://github.com/KarthikUdyawar/data-cleaner/releases/tag/v0.4)

If you encounter any further issues or have additional feedback, please let me know. Thank you for your contribution and patience!
